codecov:
  branch: dev
  token: 1e5af6a4-d8bd-48dd-a3e4-e02aa81d58dc
  notify:
      require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        enabled: yes
        target: auto
        threshold: 1.5
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error

    patch:
      default:
        enabled: yes
        target: 0%
        threshold: 1.5
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error

    changes:
      default:
        enabled: no
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error

comment: false
